### ISSUE TITLE
could you add a tab groups bar?

### ISSUE THREAD

**Issue by boldcompany** [char101/tabgroupsbtn#2]
Your Tab Groups Button add-on is really quite excellent. However, there is a set of functionality a lot of people are looking for, that used to exist in other add-ons, but those add-ons are now in disrepair and not well-maintained, and based on old buggy code.

What many of us are looking for: It would be great if you could add a tab groups bar like in these add-ons::

https://code.google.com/p/tabgroupsmanager
https://addons.mozilla.org/en-US/firefox/addon/tabgroups-manager
https://addons.mozilla.org/en-US/firefox/addon/tab-group-bar/?src=search

The main thing that this type of add-on does extremely well is to provide a group bar, above the tab bar, which allows for extremely quick & easy group selection, tab drag-and-drop, group reordering, group renaming, etc. TabGroups Manager is a very elegant add-on and was indispensable to many people. However, even the latest new version is very buggy and it looks like it is hardly being worked on, despite interest in it.

The reason why this feature is useful is that you can very quickly organize your tabs, and because all of the groups are always on-screen, it makes it very easy to jump back and forth and remember what you're doing.

Your add-on is really great, except that there are times when I just want to use the single browser window to instantly (a) see all the groups and (b) administer all the groups and tabs in one view, without having to flip back and forth between groups.

Here is what we request:
Replicate the group bar functionality in your add-on as an optional (turn on/turn off) feature so that people who don’t like it wouldn’t have to use it. 

Could you do this?

**Comment by char101** [comment]
Added in 0.4 https://addons.mozilla.org/en-US/firefox/addon/tab-groups-button/versions/

**Comment by char101** [comment]
Note: I'm not interested in adding drag drop and other tab management functions to the toolbar. The toolbar will be simply a tab group switcher.

**Comment by boldcompany** [comment]
:(

**Comment by eaerth** [comment]
Hey, I see this is definitely closed - as the option's been implemented; however I'm into the menu on its own, not this new tab groups button. It'd be alright if maybe it functioned more like an app/pinned tab but otherwise I'd personally just get rid of it. For the way I have my browser set up, it's kind of a redundancy and I like to keep things as minimal as possible. I'm able to uncheck the toolbar so that it goes away but every time I exit or restart, it's back where it was again. I'm not sure if this is a bug or a software feature but is there any way of fixing this? I loved the other add-on because it was just a modified version of the groups menu. This new button I think I like even more, to be honest, I just want to get rid of the group tabs toolbar.

Cheers!

**Comment by char101** [comment]
I have submitted a new version that persist the toolbar visibility

**Comment by eaerth** [comment]
Beautiful! Works flawlessly. Thanks a lot for the quick update and response!
